name: Test

# Many build steps have their own caches, so each job has its own cache to improve subsequent build times.
# Build tools are configured to cache to node_modules/.cache, so they are cached independently of node_modules.
# Caches are saved every run (by keying on github.run_id), and the most recent available cache is loaded.
# See https://jongleberry.medium.com/speed-up-your-ci-and-dx-with-node-modules-cache-ac8df82b7bb0.

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - uses: ./.github/actions/cache-on-main
        with:
          path: node_modules/.cache
          key: ${{ runner.os }}-build-e2e-${{ github.run_id }}
          restore-keys: ${{ runner.os }}-build-e2e-
      - run: yarn build:e2e
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
      - uses: actions/upload-artifact@v3
        with:
          name: build-e2e
          path: build
          if-no-files-found: error
